export default function FindSitemapInstructions() {
    return (
        <div className="p-6 bg-air-superiority-blue/20 rounded-lg mb-6">
            <h3 className="text-lg font-bold text-delft-blue mb-2">How to Find Your Sitemap</h3>
            <ol className="list-decimal list-inside space-y-2 text-jet">
                <li>
                    <strong>Check Common Locations:</strong> Most websites have their sitemap at a standard URL. Try navigating to:
                    <ul className="list-disc list-inside ml-4 mt-1 bg-mint-cream p-2 rounded">
                        <li><code className="text-sm">yourwebsite.com/sitemap.xml</code></li>
                        <li><code className="text-sm">yourwebsite.com/sitemap_index.xml</code></li>
                    </ul>
                </li>
                <li>
                    <strong>Check `robots.txt`:</strong> Visit <code className="text-sm">yourwebsite.com/robots.txt</code>. This file often contains a line specifying the sitemap's location, like:
                    <div className="bg-mint-cream p-2 rounded mt-1">
                        <code className="text-sm">Sitemap: https://yourwebsite.com/sitemap.xml</code>
                    </div>
                </li>
                <li>
                    <strong>Use Google Search Console:</strong> If your site is registered with Google Search Console, you can find your submitted sitemaps under the "Sitemaps" section in the sidebar.
                </li>
                <li>
                    <strong>Check Your CMS/Plugin Settings:</strong> If you use a CMS like WordPress, the sitemap is often generated by an SEO plugin (e.g., Yoast SEO, Rank Math). Check the plugin's settings to find the sitemap URL.
                </li>
            </ol>
        </div>
    );
}
