<?php

namespace App\Services\Agents;

use Illuminate\Support\Arr;

/**
 * Represents a structured execution plan generated by AI.
 * 
 * The execution plan contains all the steps needed to deploy a campaign
 * to an advertising platform, along with budget allocation, optimizations,
 * and fallback strategies.
 */
class ExecutionPlan
{
    public array $steps;
    public array $budgetAllocation;
    public array $fallbackPlans;
    public string $reasoning;
    public array $rawPlan;

    public function __construct(
        array $steps,
        array $budgetAllocation,
        array $fallbackPlans,
        string $reasoning,
        array $rawPlan = []
    ) {
        $this->steps = $steps;
        $this->budgetAllocation = $budgetAllocation;
        $this->fallbackPlans = $fallbackPlans;
        $this->reasoning = $reasoning;
        $this->rawPlan = $rawPlan;
    }

    /**
     * Create an ExecutionPlan from AI-generated JSON response.
     * 
     * Expected JSON structure:
     * {
     *   "campaign_structure": {...},
     *   "creative_strategy": {...},
     *   "targeting_optimization": {...},
     *   "budget_allocation": {...},
     *   "execution_sequence": [
     *     {
     *       "step": 1,
     *       "action": "create_campaign",
     *       "parameters": {...},
     *       "reasoning": "..."
     *     }
     *   ],
     *   "fallback_plans": [...]
     * }
     * 
     * @param string $json JSON response from AI
     * @return self
     * @throws \Exception If JSON is invalid or missing required fields
     */
    public static function fromJson(string $json): self
    {
        // Strip markdown code blocks if present (e.g., ```json ... ```)
        $json = preg_replace('/^```(?:json)?\s*\n/m', '', $json);
        $json = preg_replace('/\n```\s*$/m', '', $json);
        $json = trim($json);
        
        $data = json_decode($json, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            \Illuminate\Support\Facades\Log::error('ExecutionPlan JSON parse error', [
                'error' => json_last_error_msg(),
                'json_preview' => substr($json, 0, 500)
            ]);
            throw new \Exception('Invalid JSON in execution plan: ' . json_last_error_msg());
        }

        // Log the structure we received
        \Illuminate\Support\Facades\Log::debug('ExecutionPlan parsed data structure', [
            'top_level_keys' => array_keys($data),
            'has_execution_sequence' => isset($data['execution_sequence']),
            'has_steps' => isset($data['steps']),
            'data_preview' => array_map(function($v) { 
                return is_array($v) ? '[array:'.count($v).']' : (is_string($v) ? substr($v, 0, 50) : gettype($v)); 
            }, $data)
        ]);

        // Extract execution sequence (try both 'execution_sequence' and 'steps')
        $steps = Arr::get($data, 'execution_sequence', Arr::get($data, 'steps', []));
        if (empty($steps)) {
            \Illuminate\Support\Facades\Log::error('ExecutionPlan missing execution steps', [
                'available_keys' => array_keys($data)
            ]);
            throw new \Exception('Execution plan missing execution_sequence or steps. Available keys: ' . implode(', ', array_keys($data)));
        }

        // Extract budget allocation
        $budgetAllocation = Arr::get($data, 'budget_allocation', []);

        // Extract fallback plans
        $fallbackPlans = Arr::get($data, 'fallback_plans', []);

        // Create reasoning summary from various parts
        $reasoning = self::generateReasoning($data);

        return new self($steps, $budgetAllocation, $fallbackPlans, $reasoning, $data);
    }

    /**
     * Generate a comprehensive reasoning summary from the plan data.
     * 
     * @param array $data Full plan data
     * @return string Reasoning summary
     */
    protected static function generateReasoning(array $data): string
    {
        $parts = [];

        // Campaign structure reasoning
        if (isset($data['campaign_structure']['reasoning'])) {
            $parts[] = "Campaign Structure: " . $data['campaign_structure']['reasoning'];
        }

        // Creative strategy reasoning
        if (isset($data['creative_strategy']['reasoning'])) {
            $parts[] = "Creative Strategy: " . $data['creative_strategy']['reasoning'];
        }

        // Targeting reasoning
        if (isset($data['targeting_optimization']['reasoning'])) {
            $parts[] = "Targeting: " . $data['targeting_optimization']['reasoning'];
        }

        // Budget reasoning
        if (isset($data['budget_allocation']['reasoning'])) {
            $parts[] = "Budget: " . $data['budget_allocation']['reasoning'];
        }

        return implode("\n\n", $parts);
    }

    /**
     * Get a specific step by its step number.
     * 
     * @param int $stepNumber Step number to retrieve
     * @return array|null Step data or null if not found
     */
    public function getStep(int $stepNumber): ?array
    {
        foreach ($this->steps as $step) {
            if (Arr::get($step, 'step') === $stepNumber) {
                return $step;
            }
        }
        return null;
    }

    /**
     * Get total number of steps in the plan.
     * 
     * @return int Number of steps
     */
    public function getStepCount(): int
    {
        return count($this->steps);
    }

    /**
     * Check if the plan has fallback strategies defined.
     * 
     * @return bool True if fallback plans exist
     */
    public function hasFallbackPlans(): bool
    {
        return !empty($this->fallbackPlans);
    }

    /**
     * Convert the plan to an array for logging or storage.
     * 
     * @return array Plan as array
     */
    public function toArray(): array
    {
        return [
            'steps' => $this->steps,
            'budget_allocation' => $this->budgetAllocation,
            'fallback_plans' => $this->fallbackPlans,
            'reasoning' => $this->reasoning,
            'step_count' => $this->getStepCount(),
        ];
    }

    /**
     * Get campaign structure configuration from plan.
     * 
     * @return array Campaign structure details
     */
    public function getCampaignStructure(): array
    {
        return Arr::get($this->rawPlan, 'campaign_structure', []);
    }

    /**
     * Get creative strategy from plan.
     * 
     * @return array Creative strategy details
     */
    public function getCreativeStrategy(): array
    {
        return Arr::get($this->rawPlan, 'creative_strategy', []);
    }

    /**
     * Get targeting optimization from plan.
     * 
     * @return array Targeting optimization details
     */
    public function getTargetingOptimization(): array
    {
        return Arr::get($this->rawPlan, 'targeting_optimization', []);
    }
}
