<?php

namespace App\Services\GoogleAds\DSAServices;

use App\Services\GoogleAds\BaseGoogleAdsService;
use Google\Ads\GoogleAds\V22\Common\AdTextAsset;
use Google\Ads\GoogleAds\V22\Common\ExpandedDynamicSearchAdInfo;
use Google\Ads\GoogleAds\V22\Enums\AdGroupAdStatusEnum\AdGroupAdStatus;
use Google\Ads\GoogleAds\V22\Resources\Ad;
use Google\Ads\GoogleAds\V22\Resources\AdGroupAd;
use Google\Ads\GoogleAds\V22\Services\AdGroupAdOperation;
use Google\Ads\GoogleAds\V22\Services\MutateAdGroupAdsRequest;
use Google\Ads\GoogleAds\V22\Errors\GoogleAdsException;
use Google\ApiCore\ApiException;

class CreateExpandedDynamicSearchAd extends BaseGoogleAdsService
{
    /**
     * Create an Expanded Dynamic Search Ad.
     *
     * Headlines are auto-generated by Google from the landing page content.
     * Only descriptions are required.
     *
     * @param string   $customerId
     * @param string   $adGroupResourceName
     * @param string[] $descriptions  2 descriptions, max 90 chars each
     * @return string|null  AdGroupAd resource name
     */
    public function __invoke(
        string $customerId,
        string $adGroupResourceName,
        array $descriptions
    ): ?string {
        $this->ensureClient();

        $dsaInfo = new ExpandedDynamicSearchAdInfo([
            'description'  => $descriptions[0] ?? '',
            'description2' => $descriptions[1] ?? '',
        ]);

        $ad = new Ad([
            'expanded_dynamic_search_ad' => $dsaInfo,
        ]);

        $adGroupAd = new AdGroupAd([
            'ad_group' => $adGroupResourceName,
            'ad'       => $ad,
            'status'   => AdGroupAdStatus::ENABLED,
        ]);

        $operation = new AdGroupAdOperation();
        $operation->setCreate($adGroupAd);

        try {
            $response = $this->client->getAdGroupAdServiceClient()->mutateAdGroupAds(
                new MutateAdGroupAdsRequest(['customer_id' => $customerId, 'operations' => [$operation]])
            );
            $resourceName = $response->getResults()[0]->getResourceName();
            $this->logInfo("Created DSA ad: {$resourceName}");
            return $resourceName;
        } catch (GoogleAdsException|ApiException $e) {
            $this->logError('CreateExpandedDynamicSearchAd failed: ' . $e->getMessage());
            return null;
        }
    }
}
