<x-mail::message>
# 🚀 Your {{ $totalAssets }} Ads Are Ready to Launch

Hi {{ $user->name }},

Everything is set. Your **{{ $campaign->name }}** campaign is fully loaded and ready to deploy.

## What's Waiting in Your Dashboard:

✅ **{{ $campaign->strategies->sum('ad_copies_count') }} Ad Copy Variations** - Headlines & descriptions optimized for click-through  
✅ **{{ $campaign->strategies->sum('image_collaterals_count') }} Custom Images** - On-brand visuals generated by AI  
✅ **{{ $campaign->strategies->sum('video_collaterals_count') }} Video Ads** - High-converting video content  

All tested, all optimized, all ready to print money.

<x-mail::button :url="route('campaigns.show', $campaign)">
Deploy Your Campaign Now
</x-mail::button>

## Here's What Happens When You Click "Deploy":

1. **Connect Google Ads** (or Facebook) - Takes 60 seconds  
2. **Set your budget** - Start with as little as $10/day  
3. **Go live** - Ads launch automatically across all platforms  
4. **Watch it work** - Our AI optimizes 24/7 while you sleep  

### The Cost Breakdown:

Traditional Agency:
- Setup fee: **$2,000+**
- Monthly retainer: **$3,000-5,000**
- Creative revisions: **$500 each**
- **Total first month: ~$5,500**

Spectra:
- Setup: **$0** (you just did it for free)
- Platform fee: **$99-249/month**
- Unlimited revisions: **Included**
- **Total first month: $99**

You're literally **98% cheaper** than hiring an agency. And you get better results because our AI never sleeps.

## Still on the Fence?

We get it. But here's the thing: **every day you wait is money left on the table.**

Your competitors are running ads. Right now. Today.

Click the button below and be live in 2 minutes:

<x-mail::button :url="route('subscription.pricing')">
Start Your 7-Day Free Trial
</x-mail::button>

No credit card required. Cancel anytime. Zero risk.

Questions? Hit reply—I'll personally walk you through it.

Thanks,<br>
The {{ config('app.name') }} Team

---

<small>P.S. Your free tier expires in **7 days**. After that, we'll have to archive your campaigns. Don't lose all this work—lock it in now for $99/mo. [Secure your spot →]({{ route('subscription.pricing') }})</small>
</x-mail::message>
