<?php

namespace App\Jobs;

use App\Models\VideoCollateral;
use App\Services\GeminiService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class ExtendVideo implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 5;
    public $timeout = 900;

    public function backoff(): array
    {
        // Veo quota exhaustion (429) can take minutes to reset.
        // Delays: 5 min, 15 min, 30 min, 60 min between retries.
        return [300, 900, 1800, 3600];
    }

    public function __construct(
        protected VideoCollateral $sourceVideo,
        protected string $extensionPrompt
    ) {
    }

    public function handle(GeminiService $geminiService): void
    {
        Log::info("--- ExtendVideo Job Started ---");
        Log::info("Source VideoCollateral ID: {$this->sourceVideo->id}");
        Log::info("Extension Prompt: {$this->extensionPrompt}");

        // Permanent precondition failures — fail immediately without retry.
        if ($this->sourceVideo->status !== 'completed') {
            $this->fail(new \Exception("Source video must be completed before extension. Current status: {$this->sourceVideo->status}"));
            return;
        }

        if (!$this->sourceVideo->gemini_video_uri) {
            $this->fail(new \Exception("Source video missing Gemini URI. Cannot extend."));
            return;
        }

        $extensionCount = $this->sourceVideo->extension_count ?? 0;
        if ($extensionCount >= 20) {
            $this->fail(new \Exception("Maximum extension limit (20) reached for this video."));
            return;
        }

        try {
            // Use the original Veo generation URI stored in the DB exactly as returned
            // by Veo at generation time. The extension API requires the full download URL:
            //   https://generativelanguage.googleapis.com/v1beta/files/{FILE_ID}:download?alt=media
            // Re-uploading the video bytes to the Files API produces a new URI that Veo
            // rejects with 400 "Input video must be a video that was generated by VEO".
            $videoUri = $this->sourceVideo->gemini_video_uri;
            Log::info("ExtendVideo: Using stored Veo URI for extension", ['uri' => $videoUri]);

            // Build a context-rich prompt so Veo understands the brand, product and
            // original scene — without this, it generates a disconnected continuation.
            $enrichedPrompt = $this->buildEnrichedPrompt();

            // Start video extension
            $operationName = $geminiService->extendVideo(
                $videoUri,
                $enrichedPrompt
            );

            if (!$operationName) {
                // Transient failure (quota, network) — throw so Laravel retries with backoff().
                throw new \Exception('Failed to start video extension.');
            }

            Log::info("Video extension started successfully. Operation: {$operationName}");

            // Create new VideoCollateral record for the extended video
            $extendedVideo = VideoCollateral::create([
                'campaign_id' => $this->sourceVideo->campaign_id,
                'strategy_id' => $this->sourceVideo->strategy_id,
                'platform' => $this->sourceVideo->platform,
                'script' => $this->sourceVideo->script . "\n\n[EXTENSION " . ($extensionCount + 1) . "]: " . $this->extensionPrompt,
                'status' => 'generating',
                'operation_name' => $operationName,
                'is_active' => true,
                'parent_video_id' => $this->sourceVideo->id,
                'extension_count' => $extensionCount + 1,
                'refinement_depth' => ($this->sourceVideo->refinement_depth ?? 0) + 1,
            ]);

            Log::info("Created extended video record with ID: {$extendedVideo->id}");

            // Dispatch job to check the extension status
            CheckVideoStatus::dispatch($extendedVideo)->delay(now()->addMinutes(1));

        } catch (\Exception $e) {
            Log::error("Error in ExtendVideo job for VideoCollateral ID {$this->sourceVideo->id}: " . $e->getMessage());
            throw $e;
        }
    }

    /**
     * Build a context-rich extension prompt so Veo maintains visual and brand
     * consistency across 8-second clips.
     *
     * Without original context, Veo generates a disconnected continuation that
     * doesn't match the brand, product, or scene in the source video.
     */
    private function buildEnrichedPrompt(): string
    {
        $parts = [];

        // Extract the root voiceover script (strip any [EXTENSION x]: prefixes)
        $originalScript = trim($this->sourceVideo->script ?? '');
        $rootScript = '';
        if ($originalScript) {
            $rootScript = trim(preg_split('/\[EXTENSION \d+\]:/i', $originalScript)[0]);
        }

        // Brand / customer context
        $customer = $this->sourceVideo->campaign?->customer;
        $brandName = $customer?->name ?? '';
        $brandWebsite = $customer?->website ?? '';

        if ($brandName) {
            $parts[] = "BRAND: {$brandName}" . ($brandWebsite ? "\nWEBSITE: {$brandWebsite}" : '');
        }

        // Core instruction: this is a script-completion extension, not a generic continuation.
        // The original 8-second clip narrated only the first portion of the voiceover before
        // running out of time. This extension must pick up the narration exactly where it
        // left off and deliver the remainder of the script.
        if ($rootScript) {
            $parts[] = <<<TEXT
PURPOSE: The original 8-second video clip ran out of time before finishing its voiceover narration. This extension must seamlessly continue that narration, picking up mid-sentence or mid-thought exactly where the previous clip ended.

COMPLETE VOICEOVER SCRIPT (the narrator must finish delivering this):
"{$rootScript}"

The previous clip covered the opening portion. This 8-second extension must deliver the remainder of the script with the same narrator voice, pace, and energy — as if it is one continuous take.
TEXT;
        }

        // Additional creative direction from the user
        if ($this->extensionPrompt) {
            $parts[] = "ADDITIONAL DIRECTION: {$this->extensionPrompt}";
        }

        $parts[] = "VISUAL CONTINUITY: Maintain exact visual continuity — same subjects, lighting, colour grading, camera style, and environment as the preceding clip. This is a seamless continuation, not a new scene.";

        return implode("\n\n", $parts);
    }

    /**
     * Handle a job failure.
     */
    public function failed(\Throwable $exception): void
    {
        Log::error('ExtendVideo failed: ' . $exception->getMessage(), [
            'exception' => $exception->getTraceAsString(),
        ]);
    }
}
